// Defines redux actions
export const GET_QUESTION = 'GET_QUESTION';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION_IDS = 'GET_QUESTION_IDS';