// Defines redux actions
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const REMOVE_ALL_QUESTIONS = 'REMOVE_ALL_QUESTIONS';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';

export const GET_ANSWERS = 'GET_ANSWERS';
export const CREATE_ANSWER = 'CREATE_ANSWER';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const REMOVE_ANSWER = 'REMOVE_ANSWER';
export const REMOVE_ALL_ANSWERS = 'REMOVE_ALL_ANSWERS';
export const FETCH_ANSWERS = 'FETCH_ANSWERS';

export default {
  GET_QUESTIONS,
  CREATE_QUESTION,
  UPDATE_QUESTION,
  REMOVE_QUESTION,
  REMOVE_ALL_QUESTIONS,
  FETCH_QUESTIONS,
  GET_ANSWERS,
  CREATE_ANSWER,
  UPDATE_ANSWER,
  REMOVE_ANSWER,
  REMOVE_ALL_ANSWERS,
  FETCH_ANSWERS
}
